v1.2.0

diff --git a/src/mmlong2-lite b/src/mmlong2-lite
--- a/src/mmlong2-lite
+++ b/src/mmlong2-lite
@@ -1,6 +1,6 @@
 #!/bin/bash
 # DESCRIPTION: Wrapper script for running mmlong2-lite Snakemake workflow
-# AUTHOR: Mantas Sereika (mase@bio.aau.dk)
+# AUTHOR: Mantas Sereika, mase@bio.aau.dk, 2025
 # LICENSE: GNU General Public License
 
 # Pre-set default settings
@@ -17,15 +17,22 @@ sample=$(grep sample $config | cut -d" " -f2 | tr -d '\r')
 loc=$(grep loc $config | cut -d" " -f2 | tr -d '\r')
 proc=$(grep -w proc $config | cut -d" " -f2 | tr -d '\r')
 cov=$(grep reads_diffcov $config | cut -d" " -f2 | tr -d '\r')
-flye_min_ovlp=$(grep flye_ovlp $config | cut -d" " -f2 | tr -d '\r')
+assembler=$(grep assembler $config | cut -d" " -f2 | tr -d '\r')
+custom_assembly=$(grep custom_assembly $config | cut -d" " -f2 | tr -d '\r')
+assembly_info=$(grep assembly_info $config | cut -d" " -f2 | tr -d '\r')
+myloasm_min_cov=$(grep myloasm_cov $config | cut -d" " -f2 | tr -d '\r')
+myloasm_min_ovlp=$(grep myloasm_ovlp $config | cut -d" " -f2 | tr -d '\r')
 flye_min_cov=$(grep flye_cov $config | cut -d" " -f2 | tr -d '\r')
-mdbg_status=$(grep mdbg_status $config | cut -d" " -f2 | tr -d '\r')
+flye_min_ovlp=$(grep flye_ovlp $config | cut -d" " -f2 | tr -d '\r')
 medaka_status=$(grep medaka_status $config | cut -d" " -f2 | tr -d '\r')
 medak_mod_pol=$(grep medak_mod_pol $config | cut -d" " -f2 | tr -d '\r')
+curation_status=$(grep curation_status $config | cut -d" " -f2 | tr -d '\r')
+tiara_status=$(grep tiara_status $config | cut -d" " -f2 | tr -d '\r')
 min_contig_len=$(grep min_contig_len $config | cut -d" " -f2 | tr -d '\r')
+min_contig_cov=$(grep min_contig_cov $config | cut -d" " -f2 | tr -d '\r')
 min_mag_len=$(grep min_mag_len $config | cut -d" " -f2 | tr -d '\r')
 semibin_mod=$(grep semibin_mod $config | cut -d" " -f2 | tr -d '\r')
-vamb_status=$(grep vamb_status $config | cut -d" " -f2 | tr -d '\r')
+cleanup_status=$(grep cleanup_status $config | cut -d" " -f2 | tr -d '\r')
 apptainer_status=$(grep apptainer_status $config | cut -d" " -f2 | tr -d '\r')
 env_1=$(grep env_1 $config | cut -d" " -f2 | tr -d '\r')
 env_2=$(grep env_2 $config | cut -d" " -f2 | tr -d '\r')
@@ -35,14 +42,17 @@ env_5=$(grep env_5 $config | cut -d" " -f2 | tr -d '\r')
 env_6=$(grep env_6 $config | cut -d" " -f2 | tr -d '\r')
 env_7=$(grep env_7 $config | cut -d" " -f2 | tr -d '\r')
 env_8=$(grep env_8 $config | cut -d" " -f2 | tr -d '\r')
+env_9=$(grep env_9 $config | cut -d" " -f2 | tr -d '\r')
 extra=""
 dryrun=""
 touch=""
-tmp=$(pwd)
 stage="OFF"
-stages=("OFF" "assembly" "polishing" "filtering" "singletons" "coverage")
+stages=("OFF" "assembly" "curation" "filtering" "singletons" "coverage" "binning")
+binmode=$(grep binmode $config | cut -d" " -f2 | tr -d '\r')
+binmodes=("fast" "default" "extended")
 rule="Finalise"
 apptainer="apptainer"
+tmp=$TMPDIR
 
 # Usage instructions for terminal interface
 usage_text="
@@ -54,29 +64,41 @@ MAIN SETTINGS:
 -pb	--pacbio_reads		Path to PacBio HiFi reads (default: $fastq)
 -o	--output_dir		Output directory name (default: $sample)
 -p	--processes		Number of processes/multi-threading (default: $proc)
+-bin	--binning_mode		Run pipeline with a specified binning mode (e.g. ${binmodes[*]})
  
 OPTIONAL SETTINGS:
 -cov 	--coverage		CSV dataframe for differential coverage binning (e.g. NP/PB/IL,/path/to/reads.fastq)
 -run	--run_until		Run pipeline until a specified stage completes (e.g. ${stages[*]/$stage})
--tmp	--temporary_dir		Directory for temporary files (default: none)
--dbg	--use_metamdbg		Use metaMDBG for assembly of PacBio reads (default: use metaFlye)
--med	--medaka_model		Medaka polishing model (default: $medak_mod_pol)
--mo	--medaka_off		Do not run Medaka polishing with Nanopore assemblies (default: use Medaka)
--vmb	--use_vamb		Use VAMB for binning (default: use GraphMB)
+-tmp	--temporary_dir		Directory for temporary files (default: $tmp)
+-fly	--use_metaflye		Use metaFlye for metagenomic assembly (default: use $assembler)
+-dbg	--use_metamdbg		Use metaMDBG for metagenomic assembly (default: use $assembler)
+-myl	--use_myloasm		Use myloasm for metagenomic assembly (default: use $assembler)
+-ca	--custom_assembly	Use a custom assembly (default: use $assembler)
+-cai	--custom_assembly_info	Optional assembly information file (metaFlye format) for custom assembly
+-med	--use_medaka		Use Medaka for polishing Nanopore assemblies (default: skip Medaka)
+-mm	--medaka_model		Medaka polishing model (default: $medak_mod_pol)
+-scr	--skip_curation		Skip assembly curation and removal of misassemblies (default: run curation)
+-who	--use_whokaryote	Use Whokaryote for identifying eukaryotic contigs (default: use Tiara)
 -sem	--semibin_model		Binning model for SemiBin (default: $semibin_mod)
--mlc	--min_len_contig	Minimum assembly contig length (default: $min_contig_len)
+-mcl	--min_contig_len	Minimum assembly contig length for binning (default: $min_contig_len)
+-mcc	--min_contig_cov	Minimum assembly contig coverage for binning (default: $min_contig_cov)
 -mlb	--min_len_bin		Minimum genomic bin size (default: $min_mag_len)
+-scl	--skip_cleanup		Skip cleanup of workflow intermediate files
+-env	--conda_envs_only	Use conda environments instead of container (default: use container)
 -h	--help			Print help information
 -v	--version		Print workflow version number
 
 ADVANCED SETTINGS:
+-mmo	--myloasm_min_ovlp	Minimum overlap between reads used by myloasm assembler (default: $myloasm_min_ovlp)
+-mmc	--myloasm_min_cov	Minimum contig coverage used by myloasm assembler (default: $myloasm_min_cov)
 -fmo	--flye_min_ovlp		Minimum overlap between reads used by Flye assembler (default: auto)
 -fmc	--flye_min_cov		Minimum initial contig coverage used by Flye assembler (default: $flye_min_cov)
--env	--conda_envs_only	Use conda environments instead of container (default: use container)
 -n	--dryrun		Print summary of jobs for the Snakemake workflow
 -t	--touch			Touch Snakemake output files
 -r	--rule			Run specified Snakemake rule
 -x	--extra_inputs		Extra inputs for Snakemake config file
+
+Aalborg University, Denmark, 2025
 
 "
 
@@ -87,23 +109,33 @@ while test $# -gt 0; do
                 -v | --version) printf -- "mmlong2-lite, version $version\n"; exit 1;;
                 -n | --dryrun) dryrun="-n"; shift;;	
                 -t | --touch) touch="--touch"; shift;;	
-                -mo | --medaka_off) medaka_status="FALSE"; shift;;	
+                -med | --use_medaka) medaka_status="TRUE"; shift;;
+                -who | --use_whokaryote) tiara_status="FALSE"; shift;;	
                 -env | --conda_envs_only) apptainer="" && apptainer_status="FALSE"; shift;;	
                 -np | --nanopore_reads) shift; fastq=$1 && mode="Nanopore-simplex"; shift;;
                 -pb | --pacbio_reads) shift; fastq=$1 && mode="PacBio-HiFi"; shift;;
                 -o | --output_dir) shift; sample=$1; shift;;
                 -p | --processes) shift; proc=$1; shift;;
                 -cov | --coverage) shift; cov=$1; shift;;
+                -bin | --binning_mode) shift; binmode=$1; shift;;
                 -run | --run_until) shift; stage=$1; shift;;
                 -tmp | --temporary_dir) shift; tmp=$1; shift;;
+                -ca | --custom_assembly) shift; custom_assembly=$1 && assembler="custom"; shift;; 
+                -cai | --custom_assembly_info) shift; assembly_info=$1; shift;; 
+                -mmo | --myloasm_min_ovlp) shift; myloasm_min_ovlp=$1; shift;;
+                -mmc | --myloasm_min_cov) shift; myloasm_min_cov=$1; shift;;
                 -fmo | --flye_min_ovlp) shift; flye_min_ovlp=$1; shift;;
                 -fmc | --flye_min_cov) shift; flye_min_cov=$1; shift;;
-                -med | --medaka_model) shift; medak_mod_pol=$1; shift;;				
-                -mlc | --min_len_contig) shift; min_contig_len=$1; shift;;
+                -mm | --medaka_model) shift; medak_mod_pol=$1 && medaka_status="TRUE"; shift;;				
+                -mcl | --min_contig_len) shift; min_contig_len=$1; shift;;
+                -mcc | --min_contig_cov) shift; min_contig_cov=$1; shift;;
                 -mlb | --min_len_bin) shift; min_mag_len=$1; shift;;
                 -sem | --semibin_model) shift; semibin_mod=$1; shift;;	
-                -dbg | --use_metamdbg) mdbg_status="TRUE"; shift;;
-                -vmb | --use_vamb) vamb_status="TRUE"; shift;;
+                -fly | --use_metaflye) assembler="metaflye"; shift;;
+                -dbg | --use_metamdbg) assembler="metamdbg"; shift;;
+                -myl | --use_myloasm) assembler="myloasm"; shift;;
+                -scr | --skip_assembly_curation) curation_status="FALSE"; shift;;
+                -scl | --skip_cleanup) cleanup_status="FALSE"; shift;;
                 -r | --rule) shift; rule=$1; shift;;				
                 -x | --extra_inputs) shift; extra=$1; shift;;				
                 *)
@@ -115,16 +147,19 @@ while test $# -gt 0; do
 
 # Basic checks
 if [[ ! " ${stages[@]} " =~ " ${stage} " ]]; then echo "ERROR: provided input for early stoppage not recognized" && exit 1; fi
+if [[ ! " ${binmodes[@]} " =~ " ${binmode} " ]]; then echo "ERROR: provided setting for binning mode not recognized" && exit 1; fi
 if [ $fastq == "none" ]; then printf -- "$usage_text" && echo "ERROR: Sequencing reads not provided" && exit 1; fi
 if [ ! -f $fastq ]; then printf -- "$usage_text" && echo "ERROR: Provided sequencing read file not found" && exit 1; fi
 if [ ! $cov == "none" ] && [ ! -f $cov ]; then printf -- "$usage_text" && echo "ERROR: Provided dataframe for differential coverage binning not found" && exit 1; fi
+if [ $assembler == "custom" ]; then if [ ! -f $custom_assembly ]; then printf -- "$usage_text" && echo "ERROR: Provided custom assembly not found" && exit 1; fi; fi
+if [ ! $assembly_info == "FALSE" ]; then if [ ! -f $assembly_info ]; then printf -- "$usage_text" && echo "ERROR: Provided custom assembly information file not found" && exit 1; fi; fi 
 bytes_left="$(df --output=avail -B 1 "$(pwd)" | tail -n 1)" && gigabytes_left=$(($bytes_left/1024**3))
 if [ $gigabytes_left -lt 100 ]; then  echo "ERROR: Less than 100 GB of free space left in working directory" && exit 1; else echo "$gigabytes_left GB of free space available in working directory"; fi
+if ! command -v conda &> /dev/null; then echo "ERROR: Dependency (((conda))) could not be found" && exit 1; fi
 if ! command -v snakemake &> /dev/null; then echo "ERROR: Dependency (((snakemake))) could not be found" && exit 1; fi
 if ! command -v singularity &> /dev/null; then echo "ERROR: Dependency (((singularity))) could not be found" && exit 1; fi
 if ! command -v dirname &> /dev/null; then echo "ERROR: Dependency (((dirname))) could not be found" && exit 1; fi
-if [ $mode == "Nanopore-simplex" ]; then mdbg_status="FALSE"; fi
-if [ $mdbg_status == "TRUE" ]; then vamb_status="TRUE"; fi
+if [ $mode == "PacBio-HiFi" ]; then medaka_status="FALSE"; fi
 
 # Setup singularity container
 if [[ "$apptainer" == "apptainer" ]] && [[ ! -d  "$script/sing-mmlong2-lite" ]]
@@ -135,16 +170,25 @@ then
 fi
 
 # Configure early stoppage
-if [ $stage == "assembly" ]; then if [ $mdbg_status == "FALSE" ]; then rule="Assembly_metaFlye"; else rule="Assembly_metaMDBG"; fi ; fi
-if [ $stage == "polishing" ]; then rule="Polishing_stitch"; fi
+if [ $stage == "assembly" ]; then if [ $assembler == "myloasm" ]; then rule="Assembly_myloasm"; fi ; fi
+if [ $stage == "assembly" ]; then if [ $assembler == "metaflye" ]; then rule="Assembly_metaFlye"; fi ; fi
+if [ $stage == "assembly" ]; then if [ $assembler == "metamdbg" ]; then rule="Assembly_metaMDBG"; fi ; fi
+if [ $stage == "assembly" ]; then if [ $assembler == "custom" ]; then rule="Assembly_custom"; fi ; fi
+if [ $stage == "curation" ]; then rule="Curation_selection" && curation_status="TRUE"; fi
 if [ $stage == "filtering" ]; then rule="Filtering_eukaryotes"; fi
 if [ $stage == "singletons" ]; then rule="Singletons_qc"; fi
 if [ $stage == "coverage" ]; then rule="Coverage_aggregate"; fi
+if [ $stage == "binning" ]; then rule="Binning_aggregate"; fi
 
 # Configure input paths
 if [[ "$sample" = *"/"* ]]; then if [[ "$sample" = /* ]]; then loc="$(dirname $sample)" && sample="$(basename $sample)"; else loc="$(pwd)/$(dirname $sample)" && sample="$(basename $sample)"; fi; else loc=$(pwd); fi
 if [[ ! "$fastq" = /* ]]; then fastq="$(pwd)/$fastq"; fi
 if [[ ! "$tmp" = /* ]]; then tmp="$(pwd)/$tmp"; fi
+if [[ ! "$cov" = /* && ! "$cov" = "none" ]]; then cov="$(pwd)/$cov"; fi
+
+# Configure cache and temporary file paths
+if [ ! -d ".pycache" ]; then mkdir .pycache; fi
+export PYTHONPYCACHEPREFIX="$(pwd)/.pycache"
 export TMPDIR=$tmp
 export SNAKEMAKE_SOURCE_CACHE=$tmp
 export SNAKEMAKE_OUTPUT_CACHE=$tmp
@@ -153,6 +197,7 @@ export XDG_CACHE_HOME=$tmp
 # Configure environments for conda-only mode
 if [[ "$apptainer" == "" ]]
 then
+conda config --set channel_priority flexible
 env_1=$script/envs/env_1.yaml
 env_2=$script/envs/env_2.yaml
 env_3=$script/envs/env_3.yaml
@@ -161,6 +206,7 @@ env_5=$script/envs/env_5.yaml
 env_6=$script/envs/env_6.yaml
 env_7=$script/envs/env_7.yaml
 env_8=$script/envs/env_8.yaml
+env_9=$script/envs/env_9.yaml
 fi
 
 # Configure Singularity bindings
@@ -177,6 +223,7 @@ done < $cov; fi;
 # Run snakemake workflow
 echo "Starting Snakemake workflow for $mode reads and $proc multi-threading instances..."
 snakemake $dryrun $touch --software-deployment-method conda $apptainer --apptainer-args "$singularity_binds" --cores $proc --resources usage=100 --rerun-incomplete --nolock -s $snakefile --configfile $config -R $rule --until $rule \
-	--config sing=$sing sample=$sample loc=$loc fastq=$fastq proc=$proc mode=$mode reads_diffcov=$cov flye_ovlp=$flye_min_ovlp flye_cov=$flye_min_cov mdbg_status=$mdbg_status medaka_status=$medaka_status medak_mod_pol=$medak_mod_pol \
-	min_contig_len=$min_contig_len min_mag_len=$min_mag_len semibin_mod=$semibin_mod vamb_status=$vamb_status apptainer_status=$apptainer_status env_1=$env_1 env_2=$env_2 env_3=$env_3 env_4=$env_4 env_5=$env_5 env_6=$env_6 env_7=$env_7 env_8=$env_8 $extra
+	--config sing=$sing sample=$sample loc=$loc fastq=$fastq proc=$proc mode=$mode reads_diffcov=$cov assembler=$assembler custom_assembly=$custom_assembly assembly_info=$assembly_info myloasm_ovlp=$myloasm_min_ovlp myloasm_cov=$myloasm_min_cov \
+  flye_ovlp=$flye_min_ovlp flye_cov=$flye_min_cov medaka_status=$medaka_status medak_mod_pol=$medak_mod_pol curation_status=$curation_status tiara_status=$tiara_status binmode=$binmode min_contig_len=$min_contig_len min_contig_cov=$min_contig_cov \
+	min_mag_len=$min_mag_len semibin_mod=$semibin_mod cleanup_status=$cleanup_status apptainer_status=$apptainer_status env_1=$env_1 env_2=$env_2 env_3=$env_3 env_4=$env_4 env_5=$env_5 env_6=$env_6 env_7=$env_7 env_8=$env_8 env_9=$env_9 $extra
 exit 0
